Repository Alais29/femhack-frontend-challenge, pull requests merged in 2023-07, with the labels that each got.

#6 added axios
  package-lock.json
  package.json
Labels: enhancement

#11 added react charjs
  package-lock.json
  package.json
Labels: enhancement

#16 feat: add API call services
  .gitignore
  services/baseUrl.js
  services/getCountries.js
  services/getCountryDataByYear.js
  services/getDataByCountry.js
  services/getUsersXYear.js
  src/App.jsx
  vite.config.js
Labels: enhancement

#18 Added vitest and RTL
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.jsx
  src/setupTest.js
  src/test/App.test.jsx
  vite.config.js
Labels: enhancement

#20 feat: add bar chart for users by year data
  src/App.jsx
  src/components/UsersYear.jsx
  src/hooks/useUsersByYear.jsx
  src/utils/getYearsByRange.js
Labels: enhancement

#21 Feature/8
  src/App.jsx
  src/components/CustomSelect.jsx
  src/components/UsersYearCountry.jsx
  src/hooks/useCountries.jsx
  src/hooks/useDatabyCountry.jsx
  src/hooks/useUsersByYear.jsx
Labels: enhancement

#23 added custom tabs
  src/App.jsx
  src/components/CustomSelect.jsx
  src/components/Layout/CustomTabs.jsx
  src/components/UsersYear.jsx
  src/components/UsersYearCountry.jsx
  src/hooks/useCountries.jsx
  src/hooks/useDatabyCountry.jsx
  src/hooks/useUsersByYear.jsx
  src/setupTest.js
  src/utils/getYearsByRange.js
Labels: enhancement

#26 Feature/24
  src/App.jsx
  src/components/charts/TopCountries.jsx
  src/components/charts/UsersYear.jsx
  src/components/charts/UsersYearCountry.jsx
  src/components/common/CustomSelect.jsx
  src/components/layout/CustomTabs.jsx
  src/hooks/useAnimation.jsx
Labels: enhancement

#27 feat: add world map with top 10 countries with internet users in 2020
  package-lock.json
  package.json
  src/App.jsx
  src/assets/countryCodes.json
  src/components/charts/WorldMap.jsx
Labels: enhancement

#45 feat: add loading and error states for hooks used to fetch data and u…
  src/components/charts/UsersYear.jsx
  src/components/charts/UsersYearCountry.jsx
  src/components/charts/WorldMap.jsx
  src/hooks/useAnimation.jsx
  src/hooks/useCountries.jsx
  src/hooks/useDatabyCountry.jsx
  src/hooks/useUsersByYear.jsx
Labels: enhancement

#46 feat: replace Tabs with Drawer, made charts responsive
  package-lock.json
  src/App.css
  src/App.jsx
  src/assets/chevronLeft.svg
  src/assets/countryCodes.json
  src/assets/menu.svg
  src/components/charts/TopCountries.jsx
  src/components/charts/UsersYear.jsx
  src/components/charts/UsersYearCountry.jsx
  src/components/charts/WorldMap.jsx
  src/components/layout/CustomTabs.jsx
  src/components/layout/PersistentDrawerLeft.jsx
  src/hooks/useCountries.jsx
  src/hooks/useDatabyCountry.jsx
Labels: enhancement

#47 Added Flags next to select
  public/countryCodes.jsonc
  src/assets/countryCodes.js
  src/components/charts/TopCountries.jsx
  src/components/charts/UsersYearCountry.jsx
  src/components/common/CustomSelect.jsx
  src/hooks/useCountries.jsx
  src/utils/getCountriesWithCode.js
Labels: enhancement

#48 feat: added logo, favicon and title
  README.md
  index.html
  public/countryCodes.jsonc
  public/favicon.ico
  src/assets/logo.png
  src/components/layout/PersistentDrawerLeft.jsx
Labels: enhancement

#51 footer added
  src/App.css
  src/App.jsx
  src/assets/github-logo.png
  src/components/layout/PersistentDrawerLeft.jsx
Labels: enhancement

#57 SEO
  README.md
  index.html
  package.json
  src/components/layout/PersistentDrawerLeft.jsx
Labels: enhancement

#59 feat: add Title component to add title and subtitle for each chart, c…
  src/App.css
  src/components/charts/CustomWorldMap.jsx
  src/components/charts/TopCountries.jsx
  src/components/charts/UsersYear.jsx
  src/components/charts/UsersYearCountry.jsx
  src/components/common/Title.jsx
  src/components/layout/PersistentDrawerLeft.jsx
  src/hooks/useCountries.jsx
  src/services/getCountryDataByYear.js
  src/services/getDataByCountry.js
Labels: enhancement

#55 Update Readme
  README.md
  public/img/lighthouse-report.png
  src/assets/react.svg
  src/components/charts/CustomWorldMap.jsx
  src/test/setupTest.js
  src/utils/countryCodes.js
  src/utils/getCountriesWithCode.js
  vite.config.js
Labels: documentation

#65 docs: add description to chart images and fix some typos
  README.md
Labels: documentation

#64 added title to drawerlist
  src/assets/menu.svg
  src/components/layout/PersistentDrawerLeft.jsx
Labels: enhancement

#66 added color to icons, chevron and menu-icon
  src/assets/chevronLeft.svg
  src/assets/menu.svg
  src/components/layout/PersistentDrawerLeft.jsx
Labels: enhancement

#68 added pictures and link to board
  README.md
  public/img/pie-chart.gif
  public/img/users-year-country.gif
  public/img/users-year.png
  public/img/users-years-country.gif
  public/img/world-map.gif
Labels: enhancement

#71 test: fix timeout issue
  src/test/CustomWorldMap.test.jsx
  src/test/TopCountries.test.jsx
  src/test/UsersYear.test.jsx
  src/test/UsersYearCountry.test.jsx
Labels: bug

#73 format code
  src/components/charts/UsersYearCountry.jsx
  src/components/layout/PersistentDrawerLeft.jsx
  src/test/CustomWorldMap.test.jsx
  src/test/TopCountries.test.jsx
  src/test/UsersYear.test.jsx
  src/test/UsersYearCountry.test.jsx
Labels: enhancement
